- id: fetter-audit
  name: Fetter Vulnerability Audit
  description: "Validate that none of the installed Python packages present in the active environment have security vulnerabilities defined on the Open Source Vulnerabilities database."
  entry: fetter -e python3 audit display
  args: []
  language: rust
  always_run: true
  pass_filenames: false
  minimum_pre_commit_version: "2.9.2"

